// This file is auto-generated by @hey-api/openapi-ts

export const apiCategoriesGetCollectionUrl = '/v4/categories';

export const apiCategoriesPostUrl = '/v4/categories';

export const apiCategoriesIdOrSlugGetUrl = '/v4/categories/{idOrSlug}';

export const apiCategoriesIdDeleteUrl = '/v4/categories/{id}';

export const apiCategoriesIdPatchUrl = '/v4/categories/{id}';

export const apiGatewaysGetCollectionUrl = '/v4/gateways';

export const apiGatewaysIdGetUrl = '/v4/gateways/{id}';

export const apiGatewayChargestotalsGetCollectionUrl = '/v4/gateway_charges/totals';

export const apiMatchCallsGetCollectionUrl = '/v4/match_calls';

export const apiMatchCallsPostUrl = '/v4/match_calls';

export const apiMatchCallsIdDeleteUrl = '/v4/match_calls/{id}';

export const apiMatchCallsIdGetUrl = '/v4/match_calls/{id}';

export const apiMatchCallsIdPatchUrl = '/v4/match_calls/{id}';

export const apiMatchCallSubmissionsGetCollectionUrl = '/v4/match_call_submissions';

export const apiMatchCallSubmissionsPostUrl = '/v4/match_call_submissions';

export const apiMatchCallSubmissionsIdGetUrl = '/v4/match_call_submissions/{id}';

export const apiMatchCallSubmissionsIdPatchUrl = '/v4/match_call_submissions/{id}';

export const apiMatchFormulasGetCollectionUrl = '/v4/match_formulas';

export const apiMatchFormulasNameGetUrl = '/v4/match_formulas/{name}';

export const apiMatchRulesGetCollectionUrl = '/v4/match_rules';

export const apiMatchRulesNameGetUrl = '/v4/match_rules/{name}';

export const apiMatchStrategiesGetCollectionUrl = '/v4/match_strategies';

export const apiMatchStrategiesPostUrl = '/v4/match_strategies';

export const apiMatchStrategiesIdDeleteUrl = '/v4/match_strategies/{id}';

export const apiMatchStrategiesIdGetUrl = '/v4/match_strategies/{id}';

export const apiMatchStrategiesIdPatchUrl = '/v4/match_strategies/{id}';

export const apiUsersIdorganizationGetUrl = '/v4/users/{id}/organization';

export const apiUsersIdorganizationPatchUrl = '/v4/users/{id}/organization';

export const apiUsersIdpersonGetUrl = '/v4/users/{id}/person';

export const apiUsersIdpersonPatchUrl = '/v4/users/{id}/person';

export const apiPingGetUrl = '/v4/ping';

export const apiProjectsIdDeleteUrl = '/v4/projects/{id}';

export const apiProjectBudgetItemsGetCollectionUrl = '/v4/project_budget_items';

export const apiProjectBudgetItemsPostUrl = '/v4/project_budget_items';

export const apiProjectBudgetItemsIdDeleteUrl = '/v4/project_budget_items/{id}';

export const apiProjectBudgetItemsIdGetUrl = '/v4/project_budget_items/{id}';

export const apiProjectBudgetItemsIdPatchUrl = '/v4/project_budget_items/{id}';

export const apiProjectCollaborationsGetCollectionUrl = '/v4/project_collaborations';

export const apiProjectCollaborationsPostUrl = '/v4/project_collaborations';

export const apiProjectCollaborationsIdDeleteUrl = '/v4/project_collaborations/{id}';

export const apiProjectCollaborationsIdGetUrl = '/v4/project_collaborations/{id}';

export const apiProjectCollaborationsIdPatchUrl = '/v4/project_collaborations/{id}';

export const apiProjectCollaborationCandidaciesGetCollectionUrl = '/v4/project_collaboration_candidacies';

export const apiProjectCollaborationCandidaciesPostUrl = '/v4/project_collaboration_candidacies';

export const apiProjectCollaborationCandidaciesIdDeleteUrl = '/v4/project_collaboration_candidacies/{id}';

export const apiProjectCollaborationCandidaciesIdGetUrl = '/v4/project_collaboration_candidacies/{id}';

export const apiProjectCollaborationCandidaciesIdPatchUrl = '/v4/project_collaboration_candidacies/{id}';

export const apiProjectRewardsGetCollectionUrl = '/v4/project_rewards';

export const apiProjectRewardsPostUrl = '/v4/project_rewards';

export const apiProjectRewardsIdDeleteUrl = '/v4/project_rewards/{id}';

export const apiProjectRewardsIdGetUrl = '/v4/project_rewards/{id}';

export const apiProjectRewardsIdPatchUrl = '/v4/project_rewards/{id}';

export const apiProjectRewardClaimsGetCollectionUrl = '/v4/project_reward_claims';

export const apiProjectRewardClaimsPostUrl = '/v4/project_reward_claims';

export const apiProjectRewardClaimsIdDeleteUrl = '/v4/project_reward_claims/{id}';

export const apiProjectRewardClaimsIdGetUrl = '/v4/project_reward_claims/{id}';

export const apiProjectSupportsmoneyTotalGetCollectionUrl = '/v4/project_supports/money_total';

export const apiProjectUpdatesGetCollectionUrl = '/v4/project_updates';

export const apiProjectUpdatesPostUrl = '/v4/project_updates';

export const apiProjectUpdatesIdDeleteUrl = '/v4/project_updates/{id}';

export const apiProjectUpdatesIdGetUrl = '/v4/project_updates/{id}';

export const apiProjectUpdatesIdPatchUrl = '/v4/project_updates/{id}';

export const apiTipjarsGetCollectionUrl = '/v4/tipjars';

export const apiTipjarsPostUrl = '/v4/tipjars';

export const apiTipjarsIdDeleteUrl = '/v4/tipjars/{id}';

export const apiTipjarsIdGetUrl = '/v4/tipjars/{id}';

export const apiTipjarsIdPatchUrl = '/v4/tipjars/{id}';

export const apiUsersGetCollectionUrl = '/v4/users';

export const apiUsersPostUrl = '/v4/users';

export const apiUsersIdOrHandleGetUrl = '/v4/users/{idOrHandle}';

export const apiUsersIdDeleteUrl = '/v4/users/{id}';

export const apiUsersIdPatchUrl = '/v4/users/{id}';

export const apiVersionsGetCollectionUrl = '/v4/versions';

export const apiVersionsIdGetUrl = '/v4/versions/{id}';

export const apiAccountingsGetCollectionUrl = '/v4/accountings';

export const apiAccountingsIdGetUrl = '/v4/accountings/{id}';

export const apiAccountingBalancePointsGetCollectionUrl = '/v4/accounting_balance_points';

export const apiAccountingTransactionsGetCollectionUrl = '/v4/accounting_transactions';

export const apiAccountingTransactionsIdGetUrl = '/v4/accounting_transactions/{id}';

export const apiGatewayChargesGetCollectionUrl = '/v4/gateway_charges';

export const apiGatewayChargesIdGetUrl = '/v4/gateway_charges/{id}';

export const apiGatewayChargesIdPatchUrl = '/v4/gateway_charges/{id}';

export const apiGatewayCheckoutsGetCollectionUrl = '/v4/gateway_checkouts';

export const apiGatewayCheckoutsPostUrl = '/v4/gateway_checkouts';

export const apiGatewayCheckoutsIdGetUrl = '/v4/gateway_checkouts/{id}';

export const apiGatewayCheckoutsIdPatchUrl = '/v4/gateway_checkouts/{id}';

export const apiProjectsGetCollectionUrl = '/v4/projects';

export const apiProjectsPostUrl = '/v4/projects';

export const apiProjectsIdOrSlugGetUrl = '/v4/projects/{idOrSlug}';

export const apiProjectsIdPatchUrl = '/v4/projects/{id}';

export const apiProjectSupportsGetCollectionUrl = '/v4/project_supports';

export const apiProjectSupportsIdGetUrl = '/v4/project_supports/{id}';

export const apiProjectSupportsIdPatchUrl = '/v4/project_supports/{id}';
