// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * A Category can be used by other resources as a "topic intent".\
 * For example. Projects might relate with up to 2 Categories, which are used by the Project
 * as a way to describe itself and can be used to discover similar Projects.\
 * \
 * Categories can only be modified by users with the role "ROLE_ADMIN", but can usually
 * be referenced by non-admin users in their own resources, such as Project owners.
 */
export const zCategory = z.object({
    id: z.string().optional(),
    slug: z.string().readonly().optional(),
    name: z.string(),
    locales: z.array(z.string()).readonly().optional()
});

/**
 * A Category can be used by other resources as a "topic intent".\
 * For example. Projects might relate with up to 2 Categories, which are used by the Project
 * as a way to describe itself and can be used to discover similar Projects.\
 * \
 * Categories can only be modified by users with the role "ROLE_ADMIN", but can usually
 * be referenced by non-admin users in their own resources, such as Project owners.
 */
export const zCategoryJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.string().optional(),
    slug: z.string().readonly().optional(),
    name: z.string(),
    locales: z.array(z.string()).readonly().optional()
});

/**
 * Unprocessable entity
 */
export const zConstraintViolationJson = z.object({
    status: z.int().optional().default(422),
    violations: z.array(z.object({
        propertyPath: z.string().optional(),
        message: z.string().optional()
    })).optional(),
    detail: z.string().readonly().optional(),
    type: z.string().readonly().optional(),
    title: z.string().readonly().nullish(),
    instance: z.string().readonly().nullish()
});

/**
 * Unprocessable entity
 */
export const zConstraintViolationJsonldJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    status: z.int().optional().default(422),
    violations: z.array(z.object({
        propertyPath: z.string().optional(),
        message: z.string().optional()
    })).optional(),
    detail: z.string().readonly().optional(),
    description: z.string().readonly().optional(),
    type: z.string().readonly().optional(),
    title: z.string().readonly().nullish(),
    instance: z.string().readonly().nullish()
});

/**
 * A representation of common errors.
 */
export const zError = z.object({
    title: z.string().readonly().nullish(),
    detail: z.string().readonly().nullish(),
    status: z.number().optional().default(400),
    instance: z.string().readonly().nullish(),
    type: z.string().readonly().optional()
});

/**
 * A representation of common errors.
 */
export const zErrorJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    title: z.string().readonly().nullish(),
    detail: z.string().readonly().nullish(),
    status: z.number().optional().default(400),
    instance: z.string().readonly().nullish(),
    type: z.string().readonly().optional(),
    description: z.string().readonly().nullish()
});

/**
 * Gateways represent payment services used to perform the necessary payments for Transactions between Accounts.\
 * \
 * For each Gateway there is an internal implementation that handles the creation and validation of Transactions between Accounts.
 * These implementations make use of external or internal services to gather the funds that are inside a Transaction,
 * perform corroboration of funds and store the Transactions into the system.
 */
export const zGateway = z.object({
    id: z.string().optional(),
    name: z.string().optional(),
    supports: z.array(z.enum(['single', 'recurring'])).optional()
});

/**
 * Gateways represent payment services used to perform the necessary payments for Transactions between Accounts.\
 * \
 * For each Gateway there is an internal implementation that handles the creation and validation of Transactions between Accounts.
 * These implementations make use of external or internal services to gather the funds that are inside a Transaction,
 * perform corroboration of funds and store the Transactions into the system.
 */
export const zGatewayJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.string().optional(),
    name: z.string().optional(),
    supports: z.array(z.enum(['single', 'recurring'])).optional()
});

/**
 * A Charge represents a payment item to be included in a Checkout for payment at a Gateway.
 */
export const zGatewayChargeChargeUpdationDto = z.object({
    id: z.int().readonly().optional(),
    status: z.enum([
        'to_charge',
        'in_charge',
        'to_refund',
        'refunded',
        'to_wallet',
        'walleted'
    ]).optional()
});

/**
 * A GatewayCheckout represents a payment session with a Gateway.
 */
export const zGatewayCheckoutCheckoutUpdationDto = z.object({
    id: z.int().readonly().optional(),
    refund: z.enum(['to_wallet', 'to_gateway']).optional()
});

export const zGatewayLink = z.object({
    method: z.string().optional(),
    type: z.enum(['debug', 'payment']).optional(),
    url: z.string().optional(),
    rel: z.string().nullish()
});

export const zGatewayLinkJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    method: z.string().optional(),
    type: z.enum(['debug', 'payment']).optional(),
    url: z.string().optional(),
    rel: z.string().nullish()
});

export const zLink = z.object({
    url: z.string().optional(),
    rel: z.string().nullish()
});

export const zLinkJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    url: z.string().optional(),
    rel: z.string().nullish()
});

/**
 * MatchCallSubmissions represent the will of a Project to be held under a MatchCall and receive matchfunding financement.
 */
export const zMatchCallSubmission = z.object({
    id: z.int().readonly().optional(),
    call: z.string().readonly().optional(),
    project: z.string().readonly().optional(),
    status: z.enum([
        'to_review',
        'in_review',
        'accepted',
        'rejected'
    ]).optional().default('to_review')
});

/**
 * MatchCallSubmissions represent the will of a Project to be held under a MatchCall and receive matchfunding financement.
 */
export const zMatchCallSubmissionMatchCallSubmissionCreationDto = z.object({
    call: z.string(),
    project: z.string()
});

/**
 * MatchCallSubmissions represent the will of a Project to be held under a MatchCall and receive matchfunding financement.
 */
export const zMatchCallSubmissionMatchCallSubmissionCreationDtoJsonld = z.object({
    call: z.string(),
    project: z.string()
});

/**
 * MatchCallSubmissions represent the will of a Project to be held under a MatchCall and receive matchfunding financement.
 */
export const zMatchCallSubmissionJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.int().readonly().optional(),
    call: z.string().readonly().optional(),
    project: z.string().readonly().optional(),
    status: z.enum([
        'to_review',
        'in_review',
        'accepted',
        'rejected'
    ]).optional().default('to_review')
});

/**
 * A MatchFormula is a predefined code implementation for matching funds in Transactions under a MatchCall.
 * MatchFormulas can be chosen by the managers in a MatchCall and their behaviour fine-tuned.
 */
export const zMatchFormula = z.object({
    name: z.string().readonly().optional(),
    expression: z.string().readonly().optional()
});

/**
 * A MatchFormula is a predefined code implementation for matching funds in Transactions under a MatchCall.
 * MatchFormulas can be chosen by the managers in a MatchCall and their behaviour fine-tuned.
 */
export const zMatchFormulaJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    name: z.string().readonly().optional(),
    expression: z.string().readonly().optional()
});

/**
 * A MatchRule is a predefined code implementation for validating
 * that a match making condition is met when there is a Charge to be matched.
 */
export const zMatchRule = z.object({
    name: z.string().readonly().optional(),
    description: z.string().readonly().optional()
});

/**
 * A MatchRule is a predefined code implementation for validating
 * that a match making condition is met when there is a Charge to be matched.
 */
export const zMatchRuleJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    name: z.string().readonly().optional(),
    description: z.string().readonly().optional()
});

export const zMoneyInput = z.object({
    amount: z.int().gt(0),
    currency: z.string()
});

export const zChargeCreationDto = z.object({
    type: z.enum(['single', 'recurring']).default('single'),
    title: z.string(),
    description: z.string().nullish(),
    target: z.string(),
    money: zMoneyInput
});

/**
 * A GatewayCheckout represents a payment session with a Gateway.
 */
export const zGatewayCheckoutCheckoutCreationDto = z.object({
    gateway: z.string(),
    origin: z.string(),
    charges: z.array(zChargeCreationDto).min(1),
    returnUrl: z.url(),
    refund: z.enum(['to_wallet', 'to_gateway']).optional().default('to_wallet')
});

/**
 * A MatchStrategy defines how will a MatchCall perform the match-making process.
 * \
 * The match-making flow is:
 * 1. A Project accepted in a MatchCall receives a successful Charge.
 * 2. The match-making loads the MatchCall's MatchStrategies.
 * 3. For each MatchStrategy the rules are executed, if one rule fails the match-making is cancelled for the strategy.
 * 3. The first valid MatchStrategy's formula function is passed the respective limit, factor and money of the MatchAgainst.
 * 4. The result of the MatchStrategy formula function execution is put in a Transaction from the MatchCall to the Project.
 */
export const zMatchStrategy = z.object({
    id: z.int().readonly().optional(),
    call: z.string(),
    ranking: z.int().gte(0).optional().default(0),
    rules: z.array(z.string()).optional(),
    formula: z.string(),
    limit: zMoneyInput,
    factor: z.number().gt(0),
    against: z.enum([
        'charge',
        'budget_min',
        'budget_opt'
    ]).optional().default('charge')
});

export const zMoneyInputJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    amount: z.int().gt(0),
    currency: z.string()
});

export const zChargeCreationDtoJsonld = z.object({
    type: z.enum(['single', 'recurring']).default('single'),
    title: z.string(),
    description: z.string().nullish(),
    target: z.string(),
    money: zMoneyInputJsonld
});

/**
 * A GatewayCheckout represents a payment session with a Gateway.
 */
export const zGatewayCheckoutCheckoutCreationDtoJsonld = z.object({
    gateway: z.string(),
    origin: z.string(),
    charges: z.array(zChargeCreationDtoJsonld).min(1),
    returnUrl: z.url(),
    refund: z.enum(['to_wallet', 'to_gateway']).optional().default('to_wallet')
});

/**
 * A MatchStrategy defines how will a MatchCall perform the match-making process.
 * \
 * The match-making flow is:
 * 1. A Project accepted in a MatchCall receives a successful Charge.
 * 2. The match-making loads the MatchCall's MatchStrategies.
 * 3. For each MatchStrategy the rules are executed, if one rule fails the match-making is cancelled for the strategy.
 * 3. The first valid MatchStrategy's formula function is passed the respective limit, factor and money of the MatchAgainst.
 * 4. The result of the MatchStrategy formula function execution is put in a Transaction from the MatchCall to the Project.
 */
export const zMatchStrategyJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.int().readonly().optional(),
    call: z.string(),
    ranking: z.int().gte(0).optional().default(0),
    rules: z.array(z.string()).optional(),
    formula: z.string(),
    limit: zMoneyInputJsonld,
    factor: z.number().gt(0),
    against: z.enum([
        'charge',
        'budget_min',
        'budget_opt'
    ]).optional().default('charge')
});

/**
 * Sometimes an Organization is behind a User account,
 * we keep their data separated from the User record to allow for other User types,
 * like the ones owned by an individual, to exist all at the same level.\
 * \
 * All Organization records are only visible to their respective owners and platform admins.
 * Sensitive data is encrypted before being stored in the database.
 */
export const zOrganization = z.object({
    user: z.string().readonly().optional(),
    taxId: z.string(),
    legalName: z.string(),
    businessName: z.string().optional()
});

/**
 * Sometimes an Organization is behind a User account,
 * we keep their data separated from the User record to allow for other User types,
 * like the ones owned by an individual, to exist all at the same level.\
 * \
 * All Organization records are only visible to their respective owners and platform admins.
 * Sensitive data is encrypted before being stored in the database.
 */
export const zOrganizationJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    user: z.string().readonly().optional(),
    taxId: z.string(),
    legalName: z.string(),
    businessName: z.string().optional()
});

/**
 * Most times a real person is behind a User account,
 * we keep their data separated from the User record to allow for other User types,
 * like the ones owned by an organization, to exist all at the same level.\
 * \
 * All Person records are only visible to their respective owners and platform admins.
 * Sensitive personal data is encrypted before being stored in the database.
 */
export const zPerson = z.object({
    user: z.string().readonly().optional(),
    taxId: z.string().optional(),
    firstName: z.string().optional(),
    lastName: z.string().optional()
});

/**
 * Most times a real person is behind a User account,
 * we keep their data separated from the User record to allow for other User types,
 * like the ones owned by an organization, to exist all at the same level.\
 * \
 * All Person records are only visible to their respective owners and platform admins.
 * Sensitive personal data is encrypted before being stored in the database.
 */
export const zPersonJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    user: z.string().readonly().optional(),
    taxId: z.string().optional(),
    firstName: z.string().optional(),
    lastName: z.string().optional()
});

export const zPing = z.object({
    time: z.int().optional(),
    message: z.string().optional()
});

export const zPingJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    time: z.int().optional(),
    message: z.string().optional()
});

/**
 * A Project's budget is composed via BudgetItem records.\
 * \
 * Each BudgetItem describes one specific monetary necessity. The total budget of a Project is then calculated from the related BudgetItems.
 */
export const zProjectBudgetItem = z.object({
    id: z.int().readonly().optional(),
    project: z.string(),
    type: z.enum([
        'infrastructure',
        'material',
        'task'
    ]),
    title: z.string(),
    description: z.string(),
    money: zMoneyInput,
    deadline: z.enum(['minimum', 'optimum']),
    locales: z.array(z.string()).readonly().optional()
});

/**
 * A Project's budget is composed via BudgetItem records.\
 * \
 * Each BudgetItem describes one specific monetary necessity. The total budget of a Project is then calculated from the related BudgetItems.
 */
export const zProjectBudgetItemJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.int().readonly().optional(),
    project: z.string(),
    type: z.enum([
        'infrastructure',
        'material',
        'task'
    ]),
    title: z.string(),
    description: z.string(),
    money: zMoneyInputJsonld,
    deadline: z.enum(['minimum', 'optimum']),
    locales: z.array(z.string()).readonly().optional()
});

export const zProjectCalendar = z.object({
    release: z.iso.datetime().nullable(),
    minimum: z.iso.datetime().nullish(),
    optimum: z.iso.datetime().nullish()
});

export const zProjectCalendarJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    release: z.iso.datetime().nullable(),
    minimum: z.iso.datetime().nullish(),
    optimum: z.iso.datetime().nullish()
});

/**
 * ProjectCollaborations are used as requests for help on specific problems that the Project might face and cannot be budgeted-in.
 */
export const zProjectCollaboration = z.object({
    id: z.int().readonly().optional(),
    project: z.string(),
    title: z.string(),
    description: z.string(),
    isFulfilled: z.boolean().default(false),
    locales: z.array(z.string()).readonly().optional(),
    dateCreated: z.iso.datetime().readonly().optional(),
    dateUpdated: z.iso.datetime().readonly().optional()
});

/**
 * ProjectCollaborations are used as requests for help on specific problems that the Project might face and cannot be budgeted-in.
 */
export const zProjectCollaborationJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.int().readonly().optional(),
    project: z.string(),
    title: z.string(),
    description: z.string(),
    isFulfilled: z.boolean().default(false),
    locales: z.array(z.string()).readonly().optional(),
    dateCreated: z.iso.datetime().readonly().optional(),
    dateUpdated: z.iso.datetime().readonly().optional()
});

/**
 * ProjectCollaborationsCandidacies represent one User's willingness to fill in for a ProjectCollaboration.
 */
export const zProjectCollaborationCandidacy = z.object({
    id: z.int().readonly().optional(),
    collaboration: z.string(),
    user: z.string(),
    description: z.string(),
    status: z.enum([
        'to_review',
        'in_review',
        'rejected',
        'approved'
    ]).default('to_review'),
    dateCreated: z.iso.datetime().readonly().optional(),
    dateUpdated: z.iso.datetime().readonly().optional()
});

/**
 * ProjectCollaborationsCandidacies represent one User's willingness to fill in for a ProjectCollaboration.
 */
export const zProjectCollaborationCandidacyJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.int().readonly().optional(),
    collaboration: z.string(),
    user: z.string(),
    description: z.string(),
    status: z.enum([
        'to_review',
        'in_review',
        'rejected',
        'approved'
    ]).default('to_review'),
    dateCreated: z.iso.datetime().readonly().optional(),
    dateUpdated: z.iso.datetime().readonly().optional()
});

/**
 * A ProjectReward is something the Project owner wishes to give in exchange for contributions to their Project.
 */
export const zProjectReward = z.object({
    id: z.int().readonly().optional(),
    project: z.string(),
    title: z.string(),
    description: z.string().nullable(),
    cover: z.url().optional(),
    money: zMoneyInput,
    isFinite: z.boolean().default(false),
    unitsTotal: z.int().nullish(),
    unitsClaimed: z.int().readonly().optional().default(0),
    unitsAvailable: z.int().readonly().optional().default(0),
    locales: z.array(z.string()).readonly().optional(),
    dateCreated: z.iso.datetime().readonly().optional(),
    dateUpdated: z.iso.datetime().readonly().optional()
});

/**
 * A ProjectReward is something the Project owner wishes to give in exchange for contributions to their Project.
 */
export const zProjectRewardJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.int().readonly().optional(),
    project: z.string(),
    title: z.string(),
    description: z.string().nullable(),
    cover: z.url().optional(),
    money: zMoneyInputJsonld,
    isFinite: z.boolean().default(false),
    unitsTotal: z.int().nullish(),
    unitsClaimed: z.int().readonly().optional().default(0),
    unitsAvailable: z.int().readonly().optional().default(0),
    locales: z.array(z.string()).readonly().optional(),
    dateCreated: z.iso.datetime().readonly().optional(),
    dateUpdated: z.iso.datetime().readonly().optional()
});

/**
 * A ProjectRewardClaim represents the will of an User who wishes to obtain one ProjectReward.
 */
export const zProjectRewardClaim = z.object({
    id: z.int().readonly().optional(),
    owner: z.string().readonly().optional(),
    charge: z.string(),
    reward: z.string()
});

/**
 * A ProjectRewardClaim represents the will of an User who wishes to obtain one ProjectReward.
 */
export const zProjectRewardClaimRewardClaimCreationDto = z.object({
    charge: z.string(),
    reward: z.string()
});

/**
 * A ProjectRewardClaim represents the will of an User who wishes to obtain one ProjectReward.
 */
export const zProjectRewardClaimRewardClaimCreationDtoJsonld = z.object({
    charge: z.string(),
    reward: z.string()
});

/**
 * A ProjectRewardClaim represents the will of an User who wishes to obtain one ProjectReward.
 */
export const zProjectRewardClaimJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.int().readonly().optional(),
    owner: z.string().readonly().optional(),
    charge: z.string(),
    reward: z.string()
});

/**
 * ProjectSupports gather Transactions going from one same origin to one same Project.\
 * \
 * MatchCalls specially might make several different Transactions to the same Project,
 * but their ProjectSupport remains the same just with updated money.
 */
export const zProjectSupportTotalizedMoney = z.object({
    amount: z.int().optional(),
    currency: z.string().optional(),
    length: z.int().optional()
});

/**
 * ProjectSupports gather Transactions going from one same origin to one same Project.\
 * \
 * MatchCalls specially might make several different Transactions to the same Project,
 * but their ProjectSupport remains the same just with updated money.
 */
export const zProjectSupportTotalizedMoneyJsonld = z.object({
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    amount: z.int().optional(),
    currency: z.string().optional(),
    length: z.int().optional()
});

/**
 * A ProjectUpdate offers records of significant news during a Project's life.\
 * \
 * Updates can be for outstanding donation amounts, achievement of goals or thresholds,
 * or any other body of information that the Project owner(s) may wish to make public to the Project's audience.
 */
export const zProjectUpdate = z.object({
    id: z.int().readonly().optional(),
    project: z.string(),
    title: z.string(),
    subtitle: z.string(),
    body: z.string(),
    date: z.iso.datetime().optional().default('now'),
    cover: z.url().optional(),
    author: z.string().readonly().nullish(),
    locales: z.array(z.string()).readonly().optional(),
    dateCreated: z.iso.datetime().readonly().optional(),
    dateUpdated: z.iso.datetime().readonly().optional()
});

/**
 * A ProjectUpdate offers records of significant news during a Project's life.\
 * \
 * Updates can be for outstanding donation amounts, achievement of goals or thresholds,
 * or any other body of information that the Project owner(s) may wish to make public to the Project's audience.
 */
export const zProjectUpdateJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.int().readonly().optional(),
    project: z.string(),
    title: z.string(),
    subtitle: z.string(),
    body: z.string(),
    date: z.iso.datetime().optional().default('now'),
    cover: z.url().optional(),
    author: z.string().readonly().nullish(),
    locales: z.array(z.string()).readonly().optional(),
    dateCreated: z.iso.datetime().readonly().optional(),
    dateUpdated: z.iso.datetime().readonly().optional()
});

export const zProjectVideo = z.object({
    src: z.string().nullish(),
    cover: z.string().nullish(),
    thumbnail: z.string().nullish()
});

export const zProjectVideoJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    src: z.string().nullish(),
    cover: z.string().nullish(),
    thumbnail: z.string().nullish()
});

export const zTerritory = z.object({
    country: z.string().nullable(),
    subLvl1: z.string().nullish(),
    subLvl2: z.string().nullish(),
    address: z.string().nullish()
});

/**
 * A MatchCall is a managed event which accepts MatchCallSubmissions from Projects to receive *matchfunding* financement.
 * This means money going to a Project in a MatchCall can be matched with funds from the MatchCall accounting.
 * \
 * \
 * MatchCallSubmissions from Projects can be accepted or rejected by the managers.
 * \
 * \
 * How and when does a MatchCall match funds is determined by the MatchStrategy.
 * Everytime there is a Charge item going to a Project accepted in a MatchCall the strategy is evaluated for matching.
 * The strategy defines a series of rules that determine if the Charge is eligible for triggering the matching of funds.
 * When a Charge is to be matched the strategy uses a MatchFormula,
 * which is a predefined implementation for common mathematical operations used to match money.
 * The formula is fine-tuned in the strategy by defining the variables in the formula.
 */
export const zMatchCall = z.object({
    id: z.int().readonly().optional(),
    accounting: z.string().readonly().optional(),
    strategies: z.array(z.string()).readonly().optional(),
    submissions: z.array(z.string()).readonly().optional(),
    managers: z.array(z.string()).optional(),
    title: z.string(),
    description: z.string().optional(),
    territory: zTerritory,
    status: z.enum([
        'in_editing',
        'in_calling',
        'in_matchmaking',
        'to_closed',
        'closed'
    ]).optional().default('in_editing')
});

/**
 * Projects describe a User-owned, community-led event that is to be discovered, developed and funded by the community.
 */
export const zProjectProjectCreationDto = z.object({
    title: z.string().min(3).regex(/^(.*[a-zA-Z]{1,}.*)$/),
    subtitle: z.string(),
    categories: z.array(z.string()).min(1).max(2),
    territory: zTerritory,
    calendar: zProjectCalendar,
    status: z.enum([
        'in_draft',
        'to_campaign_review',
        'in_campaign_review',
        'in_campaign_review.to_change',
        'in_campaign_review.to_review',
        'campaign_review.rejected',
        'to_campaign',
        'in_campaign',
        'campaign.failed',
        'campaign.cancelled',
        'to_funding_review',
        'in_funding_review',
        'in_funding_review.to_change',
        'in_funding_review.to_review',
        'funding_review.rejected',
        'to_funding',
        'in_funding',
        'funding.paid'
    ]).readonly().optional().default('in_draft')
});

/**
 * Projects describe a User-owned, community-led event that is to be discovered, developed and funded by the community.
 */
export const zProjectProjectUpdationDto = z.object({
    id: z.int().readonly().optional(),
    title: z.string().min(3).regex(/^(.*[a-zA-Z]{1,}.*)$/).optional(),
    subtitle: z.string().optional(),
    cover: z.url().optional(),
    categories: z.array(z.string()).min(1).max(2).optional(),
    territory: zTerritory.optional(),
    descBrief: z.string().min(20).optional(),
    descAbout: z.string().min(20).optional(),
    descGoal: z.string().min(20).optional(),
    descTeam: z.string().min(20).optional(),
    deadline: z.enum(['minimum', 'optimum']).optional(),
    calendar: zProjectCalendar.optional(),
    video: z.url().optional(),
    status: z.enum([
        'in_draft',
        'to_campaign_review',
        'in_campaign_review',
        'in_campaign_review.to_change',
        'in_campaign_review.to_review',
        'campaign_review.rejected',
        'to_campaign',
        'in_campaign',
        'campaign.failed',
        'campaign.cancelled',
        'to_funding_review',
        'in_funding_review',
        'in_funding_review.to_change',
        'in_funding_review.to_review',
        'funding_review.rejected',
        'to_funding',
        'in_funding',
        'funding.paid'
    ]).optional()
});

export const zTerritoryJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    country: z.string().nullable(),
    subLvl1: z.string().nullish(),
    subLvl2: z.string().nullish(),
    address: z.string().nullish()
});

/**
 * A MatchCall is a managed event which accepts MatchCallSubmissions from Projects to receive *matchfunding* financement.
 * This means money going to a Project in a MatchCall can be matched with funds from the MatchCall accounting.
 * \
 * \
 * MatchCallSubmissions from Projects can be accepted or rejected by the managers.
 * \
 * \
 * How and when does a MatchCall match funds is determined by the MatchStrategy.
 * Everytime there is a Charge item going to a Project accepted in a MatchCall the strategy is evaluated for matching.
 * The strategy defines a series of rules that determine if the Charge is eligible for triggering the matching of funds.
 * When a Charge is to be matched the strategy uses a MatchFormula,
 * which is a predefined implementation for common mathematical operations used to match money.
 * The formula is fine-tuned in the strategy by defining the variables in the formula.
 */
export const zMatchCallJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.int().readonly().optional(),
    accounting: z.string().readonly().optional(),
    strategies: z.array(z.string()).readonly().optional(),
    submissions: z.array(z.string()).readonly().optional(),
    managers: z.array(z.string()).optional(),
    title: z.string(),
    description: z.string().optional(),
    territory: zTerritoryJsonld,
    status: z.enum([
        'in_editing',
        'in_calling',
        'in_matchmaking',
        'to_closed',
        'closed'
    ]).optional().default('in_editing')
});

/**
 * Projects describe a User-owned, community-led event that is to be discovered, developed and funded by the community.
 */
export const zProjectProjectCreationDtoJsonld = z.object({
    title: z.string().min(3).regex(/^(.*[a-zA-Z]{1,}.*)$/),
    subtitle: z.string(),
    categories: z.array(z.string()).min(1).max(2),
    territory: zTerritoryJsonld,
    calendar: zProjectCalendarJsonld,
    status: z.enum([
        'in_draft',
        'to_campaign_review',
        'in_campaign_review',
        'in_campaign_review.to_change',
        'in_campaign_review.to_review',
        'campaign_review.rejected',
        'to_campaign',
        'in_campaign',
        'campaign.failed',
        'campaign.cancelled',
        'to_funding_review',
        'in_funding_review',
        'in_funding_review.to_change',
        'in_funding_review.to_review',
        'funding_review.rejected',
        'to_funding',
        'in_funding',
        'funding.paid'
    ]).readonly().optional().default('in_draft')
});

/**
 * Unlike other Money recipients a Tipjar receives money with no further goal.\
 * \
 * Tips to the platform owners and other no-purpose money can target a Tipjar.
 */
export const zTipjar = z.object({
    id: z.int().readonly().optional(),
    accounting: z.string().readonly().optional(),
    name: z.string()
});

/**
 * Unlike other Money recipients a Tipjar receives money with no further goal.\
 * \
 * Tips to the platform owners and other no-purpose money can target a Tipjar.
 */
export const zTipjarJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.int().readonly().optional(),
    accounting: z.string().readonly().optional(),
    name: z.string()
});

export const zTotalizedMoney = z.object({
    amount: z.int().optional(),
    currency: z.string().optional(),
    length: z.int().optional()
});

/**
 * A Charge represents a payment item to be included in a Checkout for payment at a Gateway.
 */
export const zGatewayChargeChargesTotalsDto = z.object({
    projects: z.int().optional(),
    money: zTotalizedMoney.optional()
});

export const zTotalizedMoneyJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    amount: z.int().optional(),
    currency: z.string().optional(),
    length: z.int().optional()
});

/**
 * A Charge represents a payment item to be included in a Checkout for payment at a Gateway.
 */
export const zGatewayChargeChargesTotalsDtoJsonld = z.object({
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    projects: z.int().optional(),
    money: zTotalizedMoneyJsonld.optional()
});

export const zTracking = z.object({
    title: z.string().optional(),
    value: z.string().optional()
});

export const zTrackingJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    title: z.string().optional(),
    value: z.string().optional()
});

/**
 * Users represent people who interact with the platform.
 */
export const zUser = z.object({
    id: z.int().readonly().optional(),
    handle: z.string().min(4).max(30).regex(/^([a-z0-9_]+)$/),
    email: z.email(),
    emailConfirmed: z.boolean().readonly().optional(),
    avatar: z.url().optional(),
    type: z.enum(['individual', 'organization']).optional(),
    roles: z.array(z.string()).optional(),
    displayName: z.string().readonly().optional(),
    person: z.string().readonly().optional(),
    organization: z.string().readonly().nullish(),
    accounting: z.string().readonly().optional(),
    projects: z.array(z.string()).readonly().optional(),
    active: z.boolean().readonly().optional(),
    links: z.array(zLink).readonly().optional(),
    territory: zTerritory.optional(),
    description: z.string().optional(),
    dateCreated: z.iso.datetime().readonly().optional(),
    dateUpdated: z.iso.datetime().readonly().optional()
});

/**
 * Users represent people who interact with the platform.
 */
export const zUserUserSignupDto = z.object({
    email: z.email(),
    password: z.string().min(8),
    type: z.enum(['individual', 'organization']).default('individual')
});

/**
 * Users represent people who interact with the platform.
 */
export const zUserUserSignupDtoJsonld = z.object({
    email: z.email(),
    password: z.string().min(8),
    type: z.enum(['individual', 'organization']).default('individual')
});

/**
 * Users represent people who interact with the platform.
 */
export const zUserJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.int().readonly().optional(),
    handle: z.string().min(4).max(30).regex(/^([a-z0-9_]+)$/),
    email: z.email(),
    emailConfirmed: z.boolean().readonly().optional(),
    avatar: z.url().optional(),
    type: z.enum(['individual', 'organization']).optional(),
    roles: z.array(z.string()).optional(),
    displayName: z.string().readonly().optional(),
    person: z.string().readonly().optional(),
    organization: z.string().readonly().nullish(),
    accounting: z.string().readonly().optional(),
    projects: z.array(z.string()).readonly().optional(),
    active: z.boolean().readonly().optional(),
    links: z.array(zLinkJsonld).readonly().optional(),
    territory: zTerritoryJsonld.optional(),
    description: z.string().optional(),
    dateCreated: z.iso.datetime().readonly().optional(),
    dateUpdated: z.iso.datetime().readonly().optional()
});

/**
 * Some resources are versioned. This means v4 keeps track of the changes performed in subsets of specific properties within these resources.\
 * \
 * This allows us to keep track of the flow and the evolution of records in the platform.
 * Looking at the changes done between one version and the next one we can reconstruct how a resource was at a certain point in time.
 */
export const zVersion = z.object({
    id: z.int().readonly().nullish(),
    action: z.string().readonly().nullish(),
    resource: z.string().readonly().optional(),
    resourceId: z.int().readonly().optional(),
    resourceVersion: z.int().readonly().nullish(),
    resourceChanges: z.unknown().optional(),
    dateCreated: z.iso.datetime().readonly().nullish()
});

/**
 * Some resources are versioned. This means v4 keeps track of the changes performed in subsets of specific properties within these resources.\
 * \
 * This allows us to keep track of the flow and the evolution of records in the platform.
 * Looking at the changes done between one version and the next one we can reconstruct how a resource was at a certain point in time.
 */
export const zVersionJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.int().readonly().nullish(),
    action: z.string().readonly().nullish(),
    resource: z.string().readonly().optional(),
    resourceId: z.int().readonly().optional(),
    resourceVersion: z.int().readonly().nullish(),
    resourceChanges: z.unknown().optional(),
    dateCreated: z.iso.datetime().readonly().nullish()
});

/**
 * v4 features an advanced economy model under the hood.
 * Accountings are implemented as a common interface for issuing and receiving Transactions,
 * which allows different resources to have money-capabalities.
 * \
 * \
 * Many different actions can trigger changes in Accountings, such as GatewayCheckouts being successfully charged.
 */
export const zAccounting = z.object({
    id: z.int().optional(),
    owner: z.string().optional(),
    ownerObject: z.string().optional(),
    currency: z.string().optional(),
    balance: z.lazy((): any => zMoneyOutput).optional()
});

/**
 * v4 features an advanced economy model under the hood.
 * Accountings are implemented as a common interface for issuing and receiving Transactions,
 * which allows different resources to have money-capabalities.
 * \
 * \
 * Many different actions can trigger changes in Accountings, such as GatewayCheckouts being successfully charged.
 */
export const zAccountingJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.int().optional(),
    owner: z.string().optional(),
    ownerObject: z.string().optional(),
    currency: z.string().optional(),
    balance: z.lazy((): any => zMoneyOutputJsonld).optional()
});

/**
 * AccountingBalancePoints represent a dated aggregate Accounting balance.\
 * \
 * Each point is the sum of money at incoming and outgoing transactions in an Accounting for a period of time,
 * you can query multiple balance points to obtain the evolution of the Accounting's balance over time.
 */
export const zAccountingBalancePoint = z.object({
    start: z.iso.datetime().optional(),
    end: z.iso.datetime().optional(),
    balance: z.lazy((): any => zMoneyOutput).optional(),
    length: z.int().optional()
});

/**
 * AccountingBalancePoints represent a dated aggregate Accounting balance.\
 * \
 * Each point is the sum of money at incoming and outgoing transactions in an Accounting for a period of time,
 * you can query multiple balance points to obtain the evolution of the Accounting's balance over time.
 */
export const zAccountingBalancePointJsonld = z.object({
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    start: z.iso.datetime().optional(),
    end: z.iso.datetime().optional(),
    balance: z.lazy((): any => zMoneyOutputJsonld).optional(),
    length: z.int().optional()
});

/**
 * AccountingTransactions represent a movement of money from one Accounting (origin) into another (target).\
 * \
 * When a transaction targets an Accounting it means that the Accounting receives it, this will add to that Accounting.
 * When a transaction originates from an Accounting the Accounting issues the transaction and it will deduct from it if,
 * specially when the transaction comes from a GatewayCharge processed by the `wallet` Gateway.\
 * \
 * AccountingTransactions are generated for each GatewayCharge in a GatewayCheckout once it becomes successful.
 */
export const zAccountingTransaction = z.object({
    id: z.int().readonly().optional(),
    money: z.lazy((): any => zMoneyOutput).optional(),
    origin: z.string().optional(),
    target: z.string().optional()
});

/**
 * AccountingTransactions represent a movement of money from one Accounting (origin) into another (target).\
 * \
 * When a transaction targets an Accounting it means that the Accounting receives it, this will add to that Accounting.
 * When a transaction originates from an Accounting the Accounting issues the transaction and it will deduct from it if,
 * specially when the transaction comes from a GatewayCharge processed by the `wallet` Gateway.\
 * \
 * AccountingTransactions are generated for each GatewayCharge in a GatewayCheckout once it becomes successful.
 */
export const zAccountingTransactionJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.int().readonly().optional(),
    money: z.lazy((): any => zMoneyOutputJsonld).optional(),
    origin: z.string().optional(),
    target: z.string().optional()
});

export const zBudget = z.object({
    minimum: z.lazy((): any => zBudgetSummary).readonly().optional(),
    optimum: z.lazy((): any => zBudgetSummary).readonly().optional()
});

export const zBudgetJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    minimum: z.lazy((): any => zBudgetSummaryJsonld).readonly().optional(),
    optimum: z.lazy((): any => zBudgetSummaryJsonld).readonly().optional()
});

export const zBudgetSummary = z.object({
    money: z.lazy((): any => zMoneyOutput).optional(),
    task: z.lazy((): any => zMoneyOutput).optional(),
    material: z.lazy((): any => zMoneyOutput).optional(),
    infra: z.lazy((): any => zMoneyOutput).optional()
});

export const zBudgetSummaryJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    money: z.lazy((): any => zMoneyOutputJsonld).optional(),
    task: z.lazy((): any => zMoneyOutputJsonld).optional(),
    material: z.lazy((): any => zMoneyOutputJsonld).optional(),
    infra: z.lazy((): any => zMoneyOutputJsonld).optional()
});

export const zConversion = z.object({
    rounding: z.string().optional(),
    from: z.lazy((): any => zMoney).optional(),
    to: z.lazy((): any => zMoney).optional(),
    rate: z.number().optional(),
    date: z.string().optional(),
    provider: z.string().optional()
});

export const zConversionJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    rounding: z.string().optional(),
    from: z.lazy((): any => zMoneyJsonld).optional(),
    to: z.lazy((): any => zMoneyJsonld).optional(),
    rate: z.number().optional(),
    date: z.string().optional(),
    provider: z.string().optional()
});

/**
 * A Charge represents a payment item to be included in a Checkout for payment at a Gateway.
 */
export const zGatewayCharge = z.object({
    id: z.int().readonly().nullish(),
    checkout: z.string().optional(),
    type: z.enum(['single', 'recurring']).default('single'),
    title: z.string(),
    description: z.string().nullish(),
    target: z.string(),
    money: z.lazy((): any => zMoneyOutput),
    status: z.enum([
        'to_charge',
        'in_charge',
        'to_refund',
        'refunded',
        'to_wallet',
        'walleted'
    ]).readonly().optional().default('to_charge'),
    dateCreated: z.iso.datetime().readonly().optional(),
    dateUpdated: z.iso.datetime().readonly().optional()
});

/**
 * A Charge represents a payment item to be included in a Checkout for payment at a Gateway.
 */
export const zGatewayChargeJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.int().readonly().nullish(),
    checkout: z.string().optional(),
    type: z.enum(['single', 'recurring']).default('single'),
    title: z.string(),
    description: z.string().nullish(),
    target: z.string(),
    money: z.lazy((): any => zMoneyOutputJsonld),
    status: z.enum([
        'to_charge',
        'in_charge',
        'to_refund',
        'refunded',
        'to_wallet',
        'walleted'
    ]).readonly().optional().default('to_charge'),
    dateCreated: z.iso.datetime().readonly().optional(),
    dateUpdated: z.iso.datetime().readonly().optional()
});

/**
 * A GatewayCheckout represents a payment session with a Gateway.
 */
export const zGatewayCheckout = z.object({
    id: z.int().readonly().optional(),
    gateway: z.string(),
    origin: z.string(),
    charges: z.array(zGatewayCharge).min(1),
    returnUrl: z.url(),
    refund: z.enum(['to_wallet', 'to_gateway']).optional().default('to_wallet'),
    status: z.enum(['to_charge', 'charged']).readonly().optional().default('to_charge'),
    links: z.array(zGatewayLink).readonly().optional(),
    trackings: z.array(zTracking).readonly().optional(),
    dateCreated: z.iso.datetime().readonly().optional(),
    dateUpdated: z.iso.datetime().readonly().optional()
});

/**
 * A GatewayCheckout represents a payment session with a Gateway.
 */
export const zGatewayCheckoutJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.int().readonly().optional(),
    gateway: z.string(),
    origin: z.string(),
    charges: z.array(zGatewayChargeJsonld).min(1),
    returnUrl: z.url(),
    refund: z.enum(['to_wallet', 'to_gateway']).optional().default('to_wallet'),
    status: z.enum(['to_charge', 'charged']).readonly().optional().default('to_charge'),
    links: z.array(zGatewayLinkJsonld).readonly().optional(),
    trackings: z.array(zTrackingJsonld).readonly().optional(),
    dateCreated: z.iso.datetime().readonly().optional(),
    dateUpdated: z.iso.datetime().readonly().optional()
});

export const zMoney = z.object({
    amount: z.int().optional(),
    currency: z.string().optional(),
    conversion: zConversion.nullish()
});

export const zMoneyJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    amount: z.int().optional(),
    currency: z.string().optional(),
    conversion: zConversionJsonld.nullish()
});

export const zMoneyOutput = z.object({
    amount: z.int().gt(0),
    currency: z.string(),
    conversion: zConversion.nullish()
});

export const zMoneyOutputJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    amount: z.int().gt(0),
    currency: z.string(),
    conversion: zConversionJsonld.nullish()
});

/**
 * Projects describe a User-owned, community-led event that is to be discovered, developed and funded by the community.
 */
export const zProject = z.object({
    id: z.int().readonly().optional(),
    slug: z.string().readonly().optional(),
    accounting: z.string().readonly().optional(),
    owner: z.string().readonly().optional(),
    title: z.string(),
    subtitle: z.string(),
    cover: z.url().optional(),
    deadline: z.enum(['minimum', 'optimum']).readonly().optional(),
    calendar: zProjectCalendar.readonly().optional(),
    categories: z.array(z.string()),
    territory: zTerritory,
    descBrief: z.string().optional(),
    descAbout: z.string().optional(),
    descGoal: z.string().optional(),
    descTeam: z.string().optional(),
    video: zProjectVideo.readonly().optional(),
    status: z.enum([
        'in_draft',
        'to_campaign_review',
        'in_campaign_review',
        'in_campaign_review.to_change',
        'in_campaign_review.to_review',
        'campaign_review.rejected',
        'to_campaign',
        'in_campaign',
        'campaign.failed',
        'campaign.cancelled',
        'to_funding_review',
        'in_funding_review',
        'in_funding_review.to_change',
        'in_funding_review.to_review',
        'funding_review.rejected',
        'to_funding',
        'in_funding',
        'funding.paid'
    ]).optional().default('in_draft'),
    rewards: z.array(z.string()).readonly().optional(),
    budget: zBudget.readonly().optional(),
    budgetItems: z.array(z.string()).readonly().optional(),
    updates: z.array(z.string()).readonly().optional(),
    matchCallSubmissions: z.array(z.string()).readonly().optional(),
    links: z.array(zLink).readonly().optional(),
    locales: z.array(z.string()).readonly().optional(),
    dateCreated: z.iso.datetime().readonly().optional(),
    dateUpdated: z.iso.datetime().readonly().optional()
});

/**
 * Projects describe a User-owned, community-led event that is to be discovered, developed and funded by the community.
 */
export const zProjectJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.int().readonly().optional(),
    slug: z.string().readonly().optional(),
    accounting: z.string().readonly().optional(),
    owner: z.string().readonly().optional(),
    title: z.string(),
    subtitle: z.string(),
    cover: z.url().optional(),
    deadline: z.enum(['minimum', 'optimum']).readonly().optional(),
    calendar: zProjectCalendarJsonld.readonly().optional(),
    categories: z.array(z.string()),
    territory: zTerritoryJsonld,
    descBrief: z.string().optional(),
    descAbout: z.string().optional(),
    descGoal: z.string().optional(),
    descTeam: z.string().optional(),
    video: zProjectVideoJsonld.readonly().optional(),
    status: z.enum([
        'in_draft',
        'to_campaign_review',
        'in_campaign_review',
        'in_campaign_review.to_change',
        'in_campaign_review.to_review',
        'campaign_review.rejected',
        'to_campaign',
        'in_campaign',
        'campaign.failed',
        'campaign.cancelled',
        'to_funding_review',
        'in_funding_review',
        'in_funding_review.to_change',
        'in_funding_review.to_review',
        'funding_review.rejected',
        'to_funding',
        'in_funding',
        'funding.paid'
    ]).optional().default('in_draft'),
    rewards: z.array(z.string()).readonly().optional(),
    budget: zBudgetJsonld.readonly().optional(),
    budgetItems: z.array(z.string()).readonly().optional(),
    updates: z.array(z.string()).readonly().optional(),
    matchCallSubmissions: z.array(z.string()).readonly().optional(),
    links: z.array(zLinkJsonld).readonly().optional(),
    locales: z.array(z.string()).readonly().optional(),
    dateCreated: z.iso.datetime().readonly().optional(),
    dateUpdated: z.iso.datetime().readonly().optional()
});

/**
 * ProjectSupports gather Transactions going from one same origin to one same Project.\
 * \
 * MatchCalls specially might make several different Transactions to the same Project,
 * but their ProjectSupport remains the same just with updated money.
 */
export const zProjectSupport = z.object({
    id: z.int().readonly().optional(),
    project: z.string().readonly().optional(),
    origin: z.string().readonly().nullish(),
    displayName: z.string().readonly().nullish(),
    displayImage: z.string().readonly().nullish(),
    transactions: z.array(z.string()).readonly().optional(),
    money: zMoneyOutput.readonly().optional(),
    anonymous: z.boolean().default(true),
    matchfunding: z.boolean().readonly().optional(),
    message: z.string().nullish()
});

/**
 * ProjectSupports gather Transactions going from one same origin to one same Project.\
 * \
 * MatchCalls specially might make several different Transactions to the same Project,
 * but their ProjectSupport remains the same just with updated money.
 */
export const zProjectSupportJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum(['http://www.w3.org/ns/hydra/core#'])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.int().readonly().optional(),
    project: z.string().readonly().optional(),
    origin: z.string().readonly().nullish(),
    displayName: z.string().readonly().nullish(),
    displayImage: z.string().readonly().nullish(),
    transactions: z.array(z.string()).readonly().optional(),
    money: zMoneyOutputJsonld.readonly().optional(),
    anonymous: z.boolean().default(true),
    matchfunding: z.boolean().readonly().optional(),
    message: z.string().nullish()
});

export const zApiCategoriesGetCollectionQuery = z.object({
    page: z.int().optional().default(1),
    itemsPerPage: z.int().gte(0).lte(100).optional().default(30),
    slug: z.string().optional(),
    'slug[]': z.array(z.string()).optional(),
    name: z.string().optional()
});

/**
 * Category collection
 */
export const zApiCategoriesGetCollectionResponse = z.array(zCategory);

/**
 * The new Category resource
 */
export const zApiCategoriesPostBody = zCategory;

/**
 * Category resource created
 */
export const zApiCategoriesPostResponse = zCategory;

export const zApiCategoriesIdOrSlugGetPath = z.object({
    idOrSlug: z.string()
});

/**
 * Category resource
 */
export const zApiCategoriesIdOrSlugGetResponse = zCategory;

export const zApiCategoriesIdDeletePath = z.object({
    id: z.string()
});

/**
 * Category resource deleted
 */
export const zApiCategoriesIdDeleteResponse = z.void();

/**
 * The updated Category resource
 */
export const zApiCategoriesIdPatchBody = zCategory;

export const zApiCategoriesIdPatchPath = z.object({
    id: z.string()
});

/**
 * Category resource updated
 */
export const zApiCategoriesIdPatchResponse = zCategory;

export const zApiGatewaysGetCollectionQuery = z.object({
    page: z.int().optional().default(1),
    itemsPerPage: z.int().gte(0).lte(100).optional().default(30)
});

/**
 * Gateway collection
 */
export const zApiGatewaysGetCollectionResponse = z.array(zGateway);

export const zApiGatewaysIdGetPath = z.object({
    id: z.string()
});

/**
 * Gateway resource
 */
export const zApiGatewaysIdGetResponse = zGateway;

export const zApiGatewayChargestotalsGetCollectionQuery = z.object({
    'checkout.gateway': z.string().optional(),
    'checkout.gateway[]': z.array(z.string()).optional(),
    'checkout.origin': z.string().optional(),
    'checkout.origin[]': z.array(z.string()).optional(),
    'checkout.trackings.value': z.string().optional(),
    'checkout.trackings.value[]': z.array(z.string()).optional(),
    type: z.string().optional(),
    'type[]': z.array(z.string()).optional(),
    title: z.string().optional(),
    'title[]': z.array(z.string()).optional(),
    target: z.string().optional(),
    'target[]': z.array(z.string()).optional(),
    'money.currency': z.string().optional(),
    'money.currency[]': z.array(z.string()).optional(),
    status: z.string().optional(),
    'status[]': z.array(z.string()).optional(),
    'money.amount[between]': z.string().optional(),
    'money.amount[gt]': z.string().optional(),
    'money.amount[gte]': z.string().optional(),
    'money.amount[lt]': z.string().optional(),
    'money.amount[lte]': z.string().optional(),
    'order[money.amount]': z.enum(['asc', 'desc']).optional().default('asc'),
    'order[status]': z.enum(['asc', 'desc']).optional().default('asc'),
    'order[dateCreated]': z.enum(['asc', 'desc']).optional().default('desc'),
    'order[dateUpdated]': z.enum(['asc', 'desc']).optional().default('desc'),
    'dateCreated[before]': z.string().optional(),
    'dateCreated[strictly_before]': z.string().optional(),
    'dateCreated[after]': z.string().optional(),
    'dateCreated[strictly_after]': z.string().optional(),
    'dateUpdated[before]': z.string().optional(),
    'dateUpdated[strictly_before]': z.string().optional(),
    'dateUpdated[after]': z.string().optional(),
    'dateUpdated[strictly_after]': z.string().optional()
});

/**
 * Charges totals
 */
export const zApiGatewayChargestotalsGetCollectionResponse = zGatewayChargeChargesTotalsDto;

export const zApiMatchCallsGetCollectionQuery = z.object({
    page: z.int().optional().default(1),
    itemsPerPage: z.int().gte(0).lte(100).optional().default(30),
    accounting: z.string().optional(),
    'accounting[]': z.array(z.string()).optional(),
    title: z.string().optional(),
    description: z.string().optional(),
    'territory.country': z.string().optional(),
    'territory.country[]': z.array(z.string()).optional(),
    'territory.subLvl1': z.string().optional(),
    'territory.subLvl1[]': z.array(z.string()).optional(),
    'territory.subLvl2': z.string().optional(),
    'territory.subLvl2[]': z.array(z.string()).optional(),
    status: z.string().optional(),
    'status[]': z.array(z.string()).optional()
});

/**
 * MatchCall collection
 */
export const zApiMatchCallsGetCollectionResponse = z.array(zMatchCall);

/**
 * The new MatchCall resource
 */
export const zApiMatchCallsPostBody = zMatchCall;

/**
 * MatchCall resource created
 */
export const zApiMatchCallsPostResponse = zMatchCall;

export const zApiMatchCallsIdDeletePath = z.object({
    id: z.string()
});

/**
 * MatchCall resource deleted
 */
export const zApiMatchCallsIdDeleteResponse = z.void();

export const zApiMatchCallsIdGetPath = z.object({
    id: z.string()
});

/**
 * MatchCall resource
 */
export const zApiMatchCallsIdGetResponse = zMatchCall;

/**
 * The updated MatchCall resource
 */
export const zApiMatchCallsIdPatchBody = zMatchCall;

export const zApiMatchCallsIdPatchPath = z.object({
    id: z.string()
});

/**
 * MatchCall resource updated
 */
export const zApiMatchCallsIdPatchResponse = zMatchCall;

export const zApiMatchCallSubmissionsGetCollectionQuery = z.object({
    page: z.int().optional().default(1),
    itemsPerPage: z.int().gte(0).lte(100).optional().default(30),
    call: z.string().optional(),
    'call[]': z.array(z.string()).optional(),
    project: z.string().optional(),
    'project[]': z.array(z.string()).optional(),
    status: z.string().optional(),
    'status[]': z.array(z.string()).optional()
});

/**
 * MatchCallSubmission collection
 */
export const zApiMatchCallSubmissionsGetCollectionResponse = z.array(zMatchCallSubmission);

/**
 * The new MatchCallSubmission resource
 */
export const zApiMatchCallSubmissionsPostBody = zMatchCallSubmissionMatchCallSubmissionCreationDto;

/**
 * MatchCallSubmission resource created
 */
export const zApiMatchCallSubmissionsPostResponse = zMatchCallSubmission;

export const zApiMatchCallSubmissionsIdGetPath = z.object({
    id: z.string()
});

/**
 * MatchCallSubmission resource
 */
export const zApiMatchCallSubmissionsIdGetResponse = zMatchCallSubmission;

/**
 * The updated MatchCallSubmission resource
 */
export const zApiMatchCallSubmissionsIdPatchBody = zMatchCallSubmission;

export const zApiMatchCallSubmissionsIdPatchPath = z.object({
    id: z.string()
});

/**
 * MatchCallSubmission resource updated
 */
export const zApiMatchCallSubmissionsIdPatchResponse = zMatchCallSubmission;

export const zApiMatchFormulasGetCollectionQuery = z.object({
    page: z.int().optional().default(1),
    itemsPerPage: z.int().gte(0).lte(100).optional().default(30)
});

/**
 * MatchFormula collection
 */
export const zApiMatchFormulasGetCollectionResponse = z.array(zMatchFormula);

export const zApiMatchFormulasNameGetPath = z.object({
    name: z.string()
});

/**
 * MatchFormula resource
 */
export const zApiMatchFormulasNameGetResponse = zMatchFormula;

export const zApiMatchRulesGetCollectionQuery = z.object({
    page: z.int().optional().default(1),
    itemsPerPage: z.int().gte(0).lte(100).optional().default(30)
});

/**
 * MatchRule collection
 */
export const zApiMatchRulesGetCollectionResponse = z.array(zMatchRule);

export const zApiMatchRulesNameGetPath = z.object({
    name: z.string()
});

/**
 * MatchRule resource
 */
export const zApiMatchRulesNameGetResponse = zMatchRule;

export const zApiMatchStrategiesGetCollectionQuery = z.object({
    page: z.int().optional().default(1),
    itemsPerPage: z.int().gte(0).lte(100).optional().default(30),
    call: z.string().optional(),
    'call[]': z.array(z.string()).optional(),
    'order[ranking]': z.enum(['asc', 'desc']).optional().default('asc')
});

/**
 * MatchStrategy collection
 */
export const zApiMatchStrategiesGetCollectionResponse = z.array(zMatchStrategy);

/**
 * The new MatchStrategy resource
 */
export const zApiMatchStrategiesPostBody = zMatchStrategy;

/**
 * MatchStrategy resource created
 */
export const zApiMatchStrategiesPostResponse = zMatchStrategy;

export const zApiMatchStrategiesIdDeletePath = z.object({
    id: z.string()
});

/**
 * MatchStrategy resource deleted
 */
export const zApiMatchStrategiesIdDeleteResponse = z.void();

export const zApiMatchStrategiesIdGetPath = z.object({
    id: z.string()
});

/**
 * MatchStrategy resource
 */
export const zApiMatchStrategiesIdGetResponse = zMatchStrategy;

/**
 * The updated MatchStrategy resource
 */
export const zApiMatchStrategiesIdPatchBody = zMatchStrategy;

export const zApiMatchStrategiesIdPatchPath = z.object({
    id: z.string()
});

/**
 * MatchStrategy resource updated
 */
export const zApiMatchStrategiesIdPatchResponse = zMatchStrategy;

export const zApiUsersIdorganizationGetPath = z.object({
    id: z.string()
});

/**
 * Organization resource
 */
export const zApiUsersIdorganizationGetResponse = zOrganization;

/**
 * The updated Organization resource
 */
export const zApiUsersIdorganizationPatchBody = zOrganization;

export const zApiUsersIdorganizationPatchPath = z.object({
    id: z.string()
});

/**
 * Organization resource updated
 */
export const zApiUsersIdorganizationPatchResponse = zOrganization;

export const zApiUsersIdpersonGetPath = z.object({
    id: z.string()
});

/**
 * Person resource
 */
export const zApiUsersIdpersonGetResponse = zPerson;

/**
 * The updated Person resource
 */
export const zApiUsersIdpersonPatchBody = zPerson;

export const zApiUsersIdpersonPatchPath = z.object({
    id: z.string()
});

/**
 * Person resource updated
 */
export const zApiUsersIdpersonPatchResponse = zPerson;

/**
 * Ping resource
 */
export const zApiPingGetResponse = zPing;

export const zApiProjectsIdDeletePath = z.object({
    id: z.string()
});

/**
 * Project resource deleted
 */
export const zApiProjectsIdDeleteResponse = z.void();

export const zApiProjectBudgetItemsGetCollectionQuery = z.object({
    page: z.int().optional().default(1),
    itemsPerPage: z.int().gte(0).lte(100).optional().default(30),
    project: z.string().optional(),
    'project[]': z.array(z.string()).optional(),
    type: z.string().optional(),
    'type[]': z.array(z.string()).optional(),
    deadline: z.string().optional(),
    'deadline[]': z.array(z.string()).optional()
});

/**
 * ProjectBudgetItem collection
 */
export const zApiProjectBudgetItemsGetCollectionResponse = z.array(zProjectBudgetItem);

/**
 * The new ProjectBudgetItem resource
 */
export const zApiProjectBudgetItemsPostBody = zProjectBudgetItem;

/**
 * ProjectBudgetItem resource created
 */
export const zApiProjectBudgetItemsPostResponse = zProjectBudgetItem;

export const zApiProjectBudgetItemsIdDeletePath = z.object({
    id: z.string()
});

/**
 * ProjectBudgetItem resource deleted
 */
export const zApiProjectBudgetItemsIdDeleteResponse = z.void();

export const zApiProjectBudgetItemsIdGetPath = z.object({
    id: z.string()
});

/**
 * ProjectBudgetItem resource
 */
export const zApiProjectBudgetItemsIdGetResponse = zProjectBudgetItem;

/**
 * The updated ProjectBudgetItem resource
 */
export const zApiProjectBudgetItemsIdPatchBody = zProjectBudgetItem;

export const zApiProjectBudgetItemsIdPatchPath = z.object({
    id: z.string()
});

/**
 * ProjectBudgetItem resource updated
 */
export const zApiProjectBudgetItemsIdPatchResponse = zProjectBudgetItem;

export const zApiProjectCollaborationsGetCollectionQuery = z.object({
    page: z.int().optional().default(1),
    itemsPerPage: z.int().gte(0).lte(100).optional().default(30),
    project: z.string().optional(),
    'project[]': z.array(z.string()).optional(),
    isFulfilled: z.boolean().optional(),
    'dateCreated[before]': z.string().optional(),
    'dateCreated[strictly_before]': z.string().optional(),
    'dateCreated[after]': z.string().optional(),
    'dateCreated[strictly_after]': z.string().optional(),
    'dateUpdated[before]': z.string().optional(),
    'dateUpdated[strictly_before]': z.string().optional(),
    'dateUpdated[after]': z.string().optional(),
    'dateUpdated[strictly_after]': z.string().optional(),
    'order[dateCreated]': z.enum(['asc', 'desc']).optional().default('asc'),
    'order[dateUpdated]': z.enum(['asc', 'desc']).optional().default('asc')
});

/**
 * ProjectCollaboration collection
 */
export const zApiProjectCollaborationsGetCollectionResponse = z.array(zProjectCollaboration);

/**
 * The new ProjectCollaboration resource
 */
export const zApiProjectCollaborationsPostBody = zProjectCollaboration;

/**
 * ProjectCollaboration resource created
 */
export const zApiProjectCollaborationsPostResponse = zProjectCollaboration;

export const zApiProjectCollaborationsIdDeletePath = z.object({
    id: z.string()
});

/**
 * ProjectCollaboration resource deleted
 */
export const zApiProjectCollaborationsIdDeleteResponse = z.void();

export const zApiProjectCollaborationsIdGetPath = z.object({
    id: z.string()
});

/**
 * ProjectCollaboration resource
 */
export const zApiProjectCollaborationsIdGetResponse = zProjectCollaboration;

/**
 * The updated ProjectCollaboration resource
 */
export const zApiProjectCollaborationsIdPatchBody = zProjectCollaboration;

export const zApiProjectCollaborationsIdPatchPath = z.object({
    id: z.string()
});

/**
 * ProjectCollaboration resource updated
 */
export const zApiProjectCollaborationsIdPatchResponse = zProjectCollaboration;

export const zApiProjectCollaborationCandidaciesGetCollectionQuery = z.object({
    page: z.int().optional().default(1),
    itemsPerPage: z.int().gte(0).lte(100).optional().default(30),
    collaboration: z.string().optional(),
    'collaboration[]': z.array(z.string()).optional(),
    user: z.string().optional(),
    'user[]': z.array(z.string()).optional(),
    description: z.string().optional(),
    status: z.string().optional(),
    'status[]': z.array(z.string()).optional(),
    'dateCreated[before]': z.string().optional(),
    'dateCreated[strictly_before]': z.string().optional(),
    'dateCreated[after]': z.string().optional(),
    'dateCreated[strictly_after]': z.string().optional(),
    'dateUpdated[before]': z.string().optional(),
    'dateUpdated[strictly_before]': z.string().optional(),
    'dateUpdated[after]': z.string().optional(),
    'dateUpdated[strictly_after]': z.string().optional(),
    'order[dateCreated]': z.enum(['asc', 'desc']).optional().default('asc'),
    'order[dateUpdated]': z.enum(['asc', 'desc']).optional().default('asc')
});

/**
 * ProjectCollaborationCandidacy collection
 */
export const zApiProjectCollaborationCandidaciesGetCollectionResponse = z.array(zProjectCollaborationCandidacy);

/**
 * The new ProjectCollaborationCandidacy resource
 */
export const zApiProjectCollaborationCandidaciesPostBody = zProjectCollaborationCandidacy;

/**
 * ProjectCollaborationCandidacy resource created
 */
export const zApiProjectCollaborationCandidaciesPostResponse = zProjectCollaborationCandidacy;

export const zApiProjectCollaborationCandidaciesIdDeletePath = z.object({
    id: z.string()
});

/**
 * ProjectCollaborationCandidacy resource deleted
 */
export const zApiProjectCollaborationCandidaciesIdDeleteResponse = z.void();

export const zApiProjectCollaborationCandidaciesIdGetPath = z.object({
    id: z.string()
});

/**
 * ProjectCollaborationCandidacy resource
 */
export const zApiProjectCollaborationCandidaciesIdGetResponse = zProjectCollaborationCandidacy;

/**
 * The updated ProjectCollaborationCandidacy resource
 */
export const zApiProjectCollaborationCandidaciesIdPatchBody = zProjectCollaborationCandidacy;

export const zApiProjectCollaborationCandidaciesIdPatchPath = z.object({
    id: z.string()
});

/**
 * ProjectCollaborationCandidacy resource updated
 */
export const zApiProjectCollaborationCandidaciesIdPatchResponse = zProjectCollaborationCandidacy;

export const zApiProjectRewardsGetCollectionQuery = z.object({
    page: z.int().optional().default(1),
    itemsPerPage: z.int().gte(0).lte(100).optional().default(30),
    project: z.string().optional(),
    'project[]': z.array(z.string()).optional(),
    'order[money.amount]': z.enum(['asc', 'desc']).optional().default('asc'),
    'order[unitsClaimed]': z.enum(['asc', 'desc']).optional().default('asc'),
    'order[unitsAvailable]': z.enum(['asc', 'desc']).optional().default('asc'),
    'order[dateCreated]': z.enum(['asc', 'desc']).optional().default('asc'),
    'order[dateUpdated]': z.enum(['asc', 'desc']).optional().default('asc'),
    isFinite: z.boolean().optional(),
    'dateCreated[before]': z.string().optional(),
    'dateCreated[strictly_before]': z.string().optional(),
    'dateCreated[after]': z.string().optional(),
    'dateCreated[strictly_after]': z.string().optional(),
    'dateUpdated[before]': z.string().optional(),
    'dateUpdated[strictly_before]': z.string().optional(),
    'dateUpdated[after]': z.string().optional(),
    'dateUpdated[strictly_after]': z.string().optional()
});

/**
 * ProjectReward collection
 */
export const zApiProjectRewardsGetCollectionResponse = z.array(zProjectReward);

/**
 * The new ProjectReward resource
 */
export const zApiProjectRewardsPostBody = zProjectReward;

/**
 * ProjectReward resource created
 */
export const zApiProjectRewardsPostResponse = zProjectReward;

export const zApiProjectRewardsIdDeletePath = z.object({
    id: z.string()
});

/**
 * ProjectReward resource deleted
 */
export const zApiProjectRewardsIdDeleteResponse = z.void();

export const zApiProjectRewardsIdGetPath = z.object({
    id: z.string()
});

/**
 * ProjectReward resource
 */
export const zApiProjectRewardsIdGetResponse = zProjectReward;

/**
 * The updated ProjectReward resource
 */
export const zApiProjectRewardsIdPatchBody = zProjectReward;

export const zApiProjectRewardsIdPatchPath = z.object({
    id: z.string()
});

/**
 * ProjectReward resource updated
 */
export const zApiProjectRewardsIdPatchResponse = zProjectReward;

export const zApiProjectRewardClaimsGetCollectionQuery = z.object({
    page: z.int().optional().default(1),
    itemsPerPage: z.int().gte(0).lte(100).optional().default(30),
    owner: z.string().optional(),
    'owner[]': z.array(z.string()).optional(),
    charge: z.string().optional(),
    'charge[]': z.array(z.string()).optional(),
    reward: z.string().optional(),
    'reward[]': z.array(z.string()).optional()
});

/**
 * ProjectRewardClaim collection
 */
export const zApiProjectRewardClaimsGetCollectionResponse = z.array(zProjectRewardClaim);

/**
 * The new ProjectRewardClaim resource
 */
export const zApiProjectRewardClaimsPostBody = zProjectRewardClaimRewardClaimCreationDto;

/**
 * ProjectRewardClaim resource created
 */
export const zApiProjectRewardClaimsPostResponse = zProjectRewardClaim;

export const zApiProjectRewardClaimsIdDeletePath = z.object({
    id: z.string()
});

/**
 * ProjectRewardClaim resource deleted
 */
export const zApiProjectRewardClaimsIdDeleteResponse = z.void();

export const zApiProjectRewardClaimsIdGetPath = z.object({
    id: z.string()
});

/**
 * ProjectRewardClaim resource
 */
export const zApiProjectRewardClaimsIdGetResponse = zProjectRewardClaim;

export const zApiProjectSupportsmoneyTotalGetCollectionQuery = z.object({
    project: z.string().optional(),
    'project[]': z.array(z.string()).optional(),
    origin: z.string().optional(),
    'origin[]': z.array(z.string()).optional(),
    anonymous: z.boolean().optional(),
    matchfunding: z.boolean().optional()
});

/**
 * Totalized money
 */
export const zApiProjectSupportsmoneyTotalGetCollectionResponse = zProjectSupportTotalizedMoney;

export const zApiProjectUpdatesGetCollectionQuery = z.object({
    page: z.int().optional().default(1),
    itemsPerPage: z.int().gte(0).lte(100).optional().default(30),
    project: z.string().optional(),
    'project[]': z.array(z.string()).optional(),
    author: z.string().optional(),
    'author[]': z.array(z.string()).optional(),
    'order[date]': z.enum(['asc', 'desc']).optional().default('asc'),
    'order[dateCreated]': z.enum(['asc', 'desc']).optional().default('asc'),
    'order[dateUpdated]': z.enum(['asc', 'desc']).optional().default('asc'),
    'dateCreated[before]': z.string().optional(),
    'dateCreated[strictly_before]': z.string().optional(),
    'dateCreated[after]': z.string().optional(),
    'dateCreated[strictly_after]': z.string().optional(),
    'dateUpdated[before]': z.string().optional(),
    'dateUpdated[strictly_before]': z.string().optional(),
    'dateUpdated[after]': z.string().optional(),
    'dateUpdated[strictly_after]': z.string().optional()
});

/**
 * ProjectUpdate collection
 */
export const zApiProjectUpdatesGetCollectionResponse = z.array(zProjectUpdate);

/**
 * The new ProjectUpdate resource
 */
export const zApiProjectUpdatesPostBody = zProjectUpdate;

/**
 * ProjectUpdate resource created
 */
export const zApiProjectUpdatesPostResponse = zProjectUpdate;

export const zApiProjectUpdatesIdDeletePath = z.object({
    id: z.string()
});

/**
 * ProjectUpdate resource deleted
 */
export const zApiProjectUpdatesIdDeleteResponse = z.void();

export const zApiProjectUpdatesIdGetPath = z.object({
    id: z.string()
});

/**
 * ProjectUpdate resource
 */
export const zApiProjectUpdatesIdGetResponse = zProjectUpdate;

/**
 * The updated ProjectUpdate resource
 */
export const zApiProjectUpdatesIdPatchBody = zProjectUpdate;

export const zApiProjectUpdatesIdPatchPath = z.object({
    id: z.string()
});

/**
 * ProjectUpdate resource updated
 */
export const zApiProjectUpdatesIdPatchResponse = zProjectUpdate;

export const zApiTipjarsGetCollectionQuery = z.object({
    page: z.int().optional().default(1),
    itemsPerPage: z.int().gte(0).lte(100).optional().default(30),
    accounting: z.string().optional(),
    'accounting[]': z.array(z.string()).optional(),
    name: z.string().optional()
});

/**
 * Tipjar collection
 */
export const zApiTipjarsGetCollectionResponse = z.array(zTipjar);

/**
 * The new Tipjar resource
 */
export const zApiTipjarsPostBody = zTipjar;

/**
 * Tipjar resource created
 */
export const zApiTipjarsPostResponse = zTipjar;

export const zApiTipjarsIdDeletePath = z.object({
    id: z.string()
});

/**
 * Tipjar resource deleted
 */
export const zApiTipjarsIdDeleteResponse = z.void();

export const zApiTipjarsIdGetPath = z.object({
    id: z.string()
});

/**
 * Tipjar resource
 */
export const zApiTipjarsIdGetResponse = zTipjar;

/**
 * The updated Tipjar resource
 */
export const zApiTipjarsIdPatchBody = zTipjar;

export const zApiTipjarsIdPatchPath = z.object({
    id: z.string()
});

/**
 * Tipjar resource updated
 */
export const zApiTipjarsIdPatchResponse = zTipjar;

export const zApiUsersGetCollectionQuery = z.object({
    page: z.int().optional().default(1),
    itemsPerPage: z.int().gte(0).lte(100).optional().default(30),
    q: z.string().optional(),
    handle: z.string().optional(),
    'order[handle]': z.enum(['asc', 'desc']).optional().default('asc'),
    'order[dateCreated]': z.enum(['asc', 'desc']).optional().default('asc'),
    'order[dateUpdated]': z.enum(['asc', 'desc']).optional().default('asc'),
    email: z.string().optional(),
    type: z.string().optional(),
    'type[]': z.array(z.string()).optional(),
    accounting: z.string().optional(),
    'accounting[]': z.array(z.string()).optional(),
    'territory.country': z.string().optional(),
    'territory.country[]': z.array(z.string()).optional(),
    'territory.subLvl1': z.string().optional(),
    'territory.subLvl1[]': z.array(z.string()).optional(),
    'territory.subLvl2': z.string().optional(),
    'territory.subLvl2[]': z.array(z.string()).optional(),
    roles: z.string().optional(),
    'roles[]': z.array(z.string()).optional(),
    'person.taxId': z.string().optional(),
    'person.taxId[]': z.array(z.string()).optional(),
    'organization.taxId': z.string().optional(),
    'organization.taxId[]': z.array(z.string()).optional(),
    active: z.boolean().optional(),
    'dateCreated[before]': z.string().optional(),
    'dateCreated[strictly_before]': z.string().optional(),
    'dateCreated[after]': z.string().optional(),
    'dateCreated[strictly_after]': z.string().optional(),
    'dateUpdated[before]': z.string().optional(),
    'dateUpdated[strictly_before]': z.string().optional(),
    'dateUpdated[after]': z.string().optional(),
    'dateUpdated[strictly_after]': z.string().optional()
});

/**
 * User collection
 */
export const zApiUsersGetCollectionResponse = z.array(zUser);

/**
 * The new User resource
 */
export const zApiUsersPostBody = zUserUserSignupDto;

/**
 * User resource created
 */
export const zApiUsersPostResponse = zUser;

export const zApiUsersIdOrHandleGetPath = z.object({
    idOrHandle: z.string()
});

/**
 * User resource
 */
export const zApiUsersIdOrHandleGetResponse = zUser;

export const zApiUsersIdDeletePath = z.object({
    id: z.string()
});

/**
 * User resource deleted
 */
export const zApiUsersIdDeleteResponse = z.void();

/**
 * The updated User resource
 */
export const zApiUsersIdPatchBody = zUser;

export const zApiUsersIdPatchPath = z.object({
    id: z.string()
});

/**
 * User resource updated
 */
export const zApiUsersIdPatchResponse = zUser;

export const zApiVersionsGetCollectionQuery = z.object({
    page: z.int().optional().default(1),
    itemsPerPage: z.int().gte(0).lte(100).optional().default(30),
    resource: z.enum([
        'GatewayCharge',
        'GatewayCheckout',
        'User'
    ]),
    resourceId: z.int()
});

/**
 * Version collection
 */
export const zApiVersionsGetCollectionResponse = z.array(zVersion);

export const zApiVersionsIdGetPath = z.object({
    id: z.string()
});

/**
 * Version resource
 */
export const zApiVersionsIdGetResponse = zVersion;

export const zApiAccountingsGetCollectionQuery = z.object({
    page: z.int().optional().default(1),
    itemsPerPage: z.int().gte(0).lte(100).optional().default(30)
});

/**
 * Accounting collection
 */
export const zApiAccountingsGetCollectionResponse = z.array(zAccounting);

export const zApiAccountingsIdGetPath = z.object({
    id: z.string()
});

/**
 * Accounting resource
 */
export const zApiAccountingsIdGetResponse = zAccounting;

export const zApiAccountingBalancePointsGetCollectionQuery = z.object({
    page: z.int().optional().default(1),
    itemsPerPage: z.int().gte(0).lte(100).optional().default(30),
    accounting: z.string(),
    start: z.iso.datetime(),
    interval: z.string().optional().default('24h'),
    end: z.iso.datetime().optional().default('now'),
    aggregate: z.boolean().optional().default(false)
});

/**
 * AccountingBalancePoint collection
 */
export const zApiAccountingBalancePointsGetCollectionResponse = z.array(zAccountingBalancePoint);

export const zApiAccountingTransactionsGetCollectionQuery = z.object({
    page: z.int().optional().default(1),
    itemsPerPage: z.int().gte(0).lte(100).optional().default(30),
    origin: z.string().optional(),
    'origin[]': z.array(z.string()).optional(),
    target: z.string().optional(),
    'target[]': z.array(z.string()).optional()
});

/**
 * AccountingTransaction collection
 */
export const zApiAccountingTransactionsGetCollectionResponse = z.array(zAccountingTransaction);

export const zApiAccountingTransactionsIdGetPath = z.object({
    id: z.string()
});

/**
 * AccountingTransaction resource
 */
export const zApiAccountingTransactionsIdGetResponse = zAccountingTransaction;

export const zApiGatewayChargesGetCollectionQuery = z.object({
    page: z.int().optional().default(1),
    itemsPerPage: z.int().gte(0).lte(100).optional().default(30),
    'checkout.gateway': z.string().optional(),
    'checkout.gateway[]': z.array(z.string()).optional(),
    'checkout.origin': z.string().optional(),
    'checkout.origin[]': z.array(z.string()).optional(),
    'checkout.trackings.value': z.string().optional(),
    'checkout.trackings.value[]': z.array(z.string()).optional(),
    type: z.string().optional(),
    'type[]': z.array(z.string()).optional(),
    title: z.string().optional(),
    'title[]': z.array(z.string()).optional(),
    target: z.string().optional(),
    'target[]': z.array(z.string()).optional(),
    'money.currency': z.string().optional(),
    'money.currency[]': z.array(z.string()).optional(),
    status: z.string().optional(),
    'status[]': z.array(z.string()).optional(),
    'money.amount[between]': z.string().optional(),
    'money.amount[gt]': z.string().optional(),
    'money.amount[gte]': z.string().optional(),
    'money.amount[lt]': z.string().optional(),
    'money.amount[lte]': z.string().optional(),
    'order[money.amount]': z.enum(['asc', 'desc']).optional().default('asc'),
    'order[status]': z.enum(['asc', 'desc']).optional().default('asc'),
    'order[dateCreated]': z.enum(['asc', 'desc']).optional().default('desc'),
    'order[dateUpdated]': z.enum(['asc', 'desc']).optional().default('desc'),
    'dateCreated[before]': z.string().optional(),
    'dateCreated[strictly_before]': z.string().optional(),
    'dateCreated[after]': z.string().optional(),
    'dateCreated[strictly_after]': z.string().optional(),
    'dateUpdated[before]': z.string().optional(),
    'dateUpdated[strictly_before]': z.string().optional(),
    'dateUpdated[after]': z.string().optional(),
    'dateUpdated[strictly_after]': z.string().optional()
});

/**
 * GatewayCharge collection
 */
export const zApiGatewayChargesGetCollectionResponse = z.array(zGatewayCharge);

export const zApiGatewayChargesIdGetPath = z.object({
    id: z.string()
});

/**
 * GatewayCharge resource
 */
export const zApiGatewayChargesIdGetResponse = zGatewayCharge;

/**
 * The updated GatewayCharge resource
 */
export const zApiGatewayChargesIdPatchBody = zGatewayChargeChargeUpdationDto;

export const zApiGatewayChargesIdPatchPath = z.object({
    id: z.string()
});

/**
 * GatewayCharge resource updated
 */
export const zApiGatewayChargesIdPatchResponse = zGatewayCharge;

export const zApiGatewayCheckoutsGetCollectionQuery = z.object({
    page: z.int().optional().default(1),
    itemsPerPage: z.int().gte(0).lte(100).optional().default(30),
    gateway: z.string().optional(),
    'gateway[]': z.array(z.string()).optional(),
    origin: z.string().optional(),
    'origin[]': z.array(z.string()).optional(),
    status: z.string().optional(),
    'status[]': z.array(z.string()).optional(),
    'trackings.value': z.string().optional(),
    'trackings.value[]': z.array(z.string()).optional()
});

/**
 * GatewayCheckout collection
 */
export const zApiGatewayCheckoutsGetCollectionResponse = z.array(zGatewayCheckout);

/**
 * The new GatewayCheckout resource
 */
export const zApiGatewayCheckoutsPostBody = zGatewayCheckoutCheckoutCreationDto;

/**
 * GatewayCheckout resource created
 */
export const zApiGatewayCheckoutsPostResponse = zGatewayCheckout;

export const zApiGatewayCheckoutsIdGetPath = z.object({
    id: z.string()
});

/**
 * GatewayCheckout resource
 */
export const zApiGatewayCheckoutsIdGetResponse = zGatewayCheckout;

/**
 * The updated GatewayCheckout resource
 */
export const zApiGatewayCheckoutsIdPatchBody = zGatewayCheckoutCheckoutUpdationDto;

export const zApiGatewayCheckoutsIdPatchPath = z.object({
    id: z.string()
});

/**
 * GatewayCheckout resource updated
 */
export const zApiGatewayCheckoutsIdPatchResponse = zGatewayCheckout;

export const zApiProjectsGetCollectionQuery = z.object({
    page: z.int().optional().default(1),
    itemsPerPage: z.int().gte(0).lte(100).optional().default(30),
    slug: z.string().optional(),
    'slug[]': z.array(z.string()).optional(),
    accounting: z.string().optional(),
    'accounting[]': z.array(z.string()).optional(),
    owner: z.string().optional(),
    'owner[]': z.array(z.string()).optional(),
    title: z.string().optional(),
    subtitle: z.string().optional(),
    categories: z.string().optional(),
    'categories[]': z.array(z.string()).optional(),
    'territory.country': z.string().optional(),
    'territory.country[]': z.array(z.string()).optional(),
    'territory.subLvl1': z.string().optional(),
    'territory.subLvl1[]': z.array(z.string()).optional(),
    'territory.subLvl2': z.string().optional(),
    'territory.subLvl2[]': z.array(z.string()).optional(),
    descBrief: z.string().optional(),
    status: z.string().optional(),
    'status[]': z.array(z.string()).optional(),
    'calendar.release[before]': z.string().optional(),
    'calendar.release[strictly_before]': z.string().optional(),
    'calendar.release[after]': z.string().optional(),
    'calendar.release[strictly_after]': z.string().optional(),
    'calendar.minimum[before]': z.string().optional(),
    'calendar.minimum[strictly_before]': z.string().optional(),
    'calendar.minimum[after]': z.string().optional(),
    'calendar.minimum[strictly_after]': z.string().optional(),
    'calendar.optimum[before]': z.string().optional(),
    'calendar.optimum[strictly_before]': z.string().optional(),
    'calendar.optimum[after]': z.string().optional(),
    'calendar.optimum[strictly_after]': z.string().optional(),
    'dateCreated[before]': z.string().optional(),
    'dateCreated[strictly_before]': z.string().optional(),
    'dateCreated[after]': z.string().optional(),
    'dateCreated[strictly_after]': z.string().optional(),
    'dateUpdated[before]': z.string().optional(),
    'dateUpdated[strictly_before]': z.string().optional(),
    'dateUpdated[after]': z.string().optional(),
    'dateUpdated[strictly_after]': z.string().optional(),
    'order[dateCreated]': z.enum(['asc', 'desc']).optional().default('asc'),
    'order[dateUpdated]': z.enum(['asc', 'desc']).optional().default('asc')
});

/**
 * Project collection
 */
export const zApiProjectsGetCollectionResponse = z.array(zProject);

/**
 * The new Project resource
 */
export const zApiProjectsPostBody = zProjectProjectCreationDto;

/**
 * Project resource created
 */
export const zApiProjectsPostResponse = zProject;

export const zApiProjectsIdOrSlugGetPath = z.object({
    idOrSlug: z.string()
});

/**
 * Project resource
 */
export const zApiProjectsIdOrSlugGetResponse = zProject;

/**
 * The updated Project resource
 */
export const zApiProjectsIdPatchBody = zProjectProjectUpdationDto;

export const zApiProjectsIdPatchPath = z.object({
    id: z.string()
});

/**
 * Project resource updated
 */
export const zApiProjectsIdPatchResponse = zProject;

export const zApiProjectSupportsGetCollectionQuery = z.object({
    page: z.int().optional().default(1),
    itemsPerPage: z.int().gte(0).lte(100).optional().default(30),
    project: z.string().optional(),
    'project[]': z.array(z.string()).optional(),
    origin: z.string().optional(),
    'origin[]': z.array(z.string()).optional(),
    anonymous: z.boolean().optional(),
    matchfunding: z.boolean().optional()
});

/**
 * ProjectSupport collection
 */
export const zApiProjectSupportsGetCollectionResponse = z.array(zProjectSupport);

export const zApiProjectSupportsIdGetPath = z.object({
    id: z.string()
});

/**
 * ProjectSupport resource
 */
export const zApiProjectSupportsIdGetResponse = zProjectSupport;

/**
 * The updated ProjectSupport resource
 */
export const zApiProjectSupportsIdPatchBody = zProjectSupport;

export const zApiProjectSupportsIdPatchPath = z.object({
    id: z.string()
});

/**
 * ProjectSupport resource updated
 */
export const zApiProjectSupportsIdPatchResponse = zProjectSupport;
