name = "goteov4web-app"
main = "@astrojs/cloudflare/entrypoints/server"
compatibility_date = "2025-06-26"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
keep_vars = true


# ============================================================================
# LOCAL DEVELOPMENT
# ============================================================================

[[d1_databases]]
binding = "DB"
database_name = "goteov4web-db"
database_id = "1f119ee7-358a-4eba-b076-40248d4f28f6"
migrations_dir = "db/migrations"


[assets]
binding = "ASSETS"
directory = "./dist"


[observability.logs]
enabled = true


# ============================================================================
# TESTING
# ============================================================================

[env.testing]
name = "goteov4web-app-testing"

routes = [
    { pattern = "testing.v4.goteo.org", zone_name = "goteo.org", custom_domain = true },
]

[[env.testing.d1_databases]]
binding = "DB"
database_name = "goteov4web-db-testing"
database_id = "5f54dc4e-811b-438b-b83e-9acee224f250"
migrations_dir = "db/migrations"


# ============================================================================
# STAGING
# ============================================================================

[env.staging]
name = "goteov4web-app-staging"

routes = [
    { pattern = "staging.v4.goteo.org", zone_name = "goteo.org", custom_domain = true },
]

[[env.staging.d1_databases]]
binding = "DB"
database_name = "goteov4web-db-staging"
database_id = "b6afee51-6e91-4e25-b7c0-fb9b166b4cda"
migrations_dir = "db/migrations"


# ============================================================================
# PRODUCTION
# ============================================================================

[env.prod]
name = "goteov4web-app-prod"

routes = [
    { pattern = "v4.goteo.org", zone_name = "goteo.org", custom_domain = true },
]

[[env.prod.d1_databases]]
binding = "DB"
database_name = "goteov4web-db-prod"
database_id = "65fe9b71-9263-400e-ae7f-7d899493ee99"
migrations_dir = "db/migrations"
