name = "goteov4web-app"
main = "@astrojs/cloudflare/entrypoints/server"
compatibility_date = "2025-06-26"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "goteov4web-db"
migrations_dir = "db/migrations"

[assets]
binding = "ASSETS"
directory = "./dist"

[observability.logs]
enabled = true
